version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - '.env'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017